server:
  port: 8888

spring:
  application:
    name: OracleConfigServer
  profiles:
    active: jdbc
  datasource:
    url: jdbc:oracle:thin:@localhost:1527/freepdb1
    username: SYSTEM
    password: efekan12345
    driver-class-name: oracle.jdbc.OracleDriver
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT PROP_KEY AS KEY, VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?