server:
  port: 8080

spring:
  application:
    name: myapp
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8888"

management:
  endpoints:
    web:
      exposure:
        include: "*"